// :::::::::::::;;::.::;;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;+X$$$&&&&;:
// ::::::::::::::::::.::;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;+X$$&&&&$X$
// :::.::::::::::::::.:;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;+X$$XXX$&&&
// :::::::::::::::.:..:;;:::::::::::::::::::++$$X+;::::::::::::::::::::::::::::::::::;;;;;+;+XXX$&&&&&&
// :::.:::::::::::::..:;;::::::::::::::::;X+;xx;xXxx;:::::::::::;xxXX+:::::::::::::::;;;;;+;x$&&&&&&&&&
// ::.:::::::::::::...:;;::::::::::::::;:+Xx;;;;+;;x+;:;;:::::::;;::x+:+x+;::::::::::;;;;;+;x$$&&&&&&&&
// ::..::::::::::.:..::;::::::::::::::xxxxxx++;;;;:::::::;:::+XXx;:xXx+;;:::+X;::::::;;;;;+;x$$$&&$x;;;
// :....:......::....:;;::::::::::::::X&&$$$$$$&&$$$XXXXXXx+;;+;::::::;::;xXX$X;::::;;;;;++;xX$$$$X+;;+
// ............::....:;::::::::::::::;X;..::::;+xXX$$&&&&$$$XX$&&&$$$$$$$$$Xx+;:::::;;;;;+++X$$$X+;;:;:
// ............:.....:;:::::::::....:;Xxx+;;:::::::::;+xXX;...:x&&&&&&&&&$&&$x;::::;;;;;++++X$$&X;;;;;:
// ............:.....:::::::.:......:+XXXxx++++;;;:::::;:::...::::;;:::;xxXx++;:::;;;;;+++++X$XX+;;;;+X
// ...........::....:::::::::.......:x$$$$$$$$$$$$$$$$$$XXXxxxxx++++;:::::+;;;:::::;;;;++++xX$x;;xX$&&&
// ...........:.....:::::::::.:::::::+;;;;;++xxXXXX$$$$$$$$$&&&&&&&&&&&&&&$$$x;::::;;;;;+++xX$$&&&&&&&&
// ...........:..::;;;;;+++++;;;;::::::::;;;;::::::::::;;;;;++++xxx+XXXXXXXx++;;::;;;;;+++;x$&&&&&&&&&&
// .........:;+;::+::;;;;++;;;;:;::::::::;;;+;;::::::++;;:;;;+++x+++xxXxxxx++;:::;;;;;;+++;x$$$$$$&&&&&
// .....:;;:;;;;..::+x&$$x::::;;:;+x+;:::::;+;++++++++xxXXx++++;+;X$$$XXxx+++;;;:;;;;;;++++X$$$$$$$$$&&
// ..:;;:::;;::..::+Xx;;xxx++;;;;;;:;;xX+;;::;;+;;++++++;+;;;:::+$$$$$$$$$$Xx;:;;;;;;;;++++X$$$$$$$$$$&
// :+$X+;:+;;:::;;;:;xxx+;:;;::::::;;:;+xXx+++;;;++Xxxx;::::::::;;;;;;;++x+++:::::;;;;+++++X$$$$$$$$$$$
// ...XX;;;;;:;;;;;xxx+;;:::::;+xxXXxx+++xxXx++++;;Xx;;::.;+.:++xXXXxxxx+++++xx+;;;;;;++++xX$$$$$$$$$$$
// .:+++++++++:..;;;;;;;::;;++;:::::+xXXXXX+;xXxxx+++;:xxXXXXxxxxxxxxxxXXx++++++xxxxxxxx+xXX$$$$$$$$$$$
// :+;+++++:::::;;:::.::::::::..:::::;::;++xx;;+xx+++++;xXXXXxxXXXXXXXXxxxxxxx++++xxxxxxXXXxX$$$$$$$$$X
// +XXX$$+::;;+;;:::.:.:::::::;++;;::;+++xxxxxx++xXXx++++xXxXXXXXXXXXxxXxxxx++xx+++xxxxxxxxxxxXX$$$$$$+
// :;XX+;;;:::;;;;;;:;::;:;+xx+;;;:::::;;;;++++xxXxx++++xxxXXxXXxXXxxxXxXXxx++++xx+xxxxxxxxxxxxxXXXX$xx
// :;;++++;;;;;;;;;++;+++xx+++;:::::::::..:+++++++;;;;;+xxxXXXXXXXxxxxxxXxxx+++++x++xxxxXxxxxxx+xXXXXXX
// :;;+x$xxxxxxxxxxxxxxxx+;::::::::::..:::....::::;:;;+xxxXXXXXXXXXXxxxXXXxx+++++xXx++xxxXxxxxxxxxXXxxx
// ..:;XX+++++++;;+++;;;;;;;;;+;;::::::......::.::;;;xxXXXXXX$XXXXXXxxxXxxx++;+++xxx+++xxxx++xxxxxxxxxx
// .......:;++++;;++++xxxxxx+++;;::::::::::::::;+;++XXXXXXX$$XxXXXXXXxxxXXxxx+++++xx++;++xx++xxxxxxxxxx
// .......:;....:;;;;+++xx+++;++++;;;;;;;;;;;;++++xXXXXXXXX$XxxXXXxxxxXXXxxxx+++xXXXx+;++xx++xxxxx++++x
// .......:;.....::::;+++++++++++x+++++++++++++++++xxxxxXX$X++xXXXXxxxXxxxxxXxx+xxXXx+++xxx++xxxxxxx++x
// .......::.....::......:xx+++++++++++++++;;;;;;;;;+++X$XXxxXXXXxx++xxxxxxxxxx+x+xXxxxxXxx++xxxXXXxxxx
// ..............::.......+xXx+;;;:;;;;;;:::::::::;;++XXXXxxXXXXXx++xxxxxxxXXXxxx++xxxXXXxxxXXXXXXXXxxx
// .+xxxxxxxxxxxxxxxxxxxxxxXXXXXxxxxxxxxxxxxxxxxx:;+xXxXXXXXX$$Xx++xxxx++xxxXxxxx++xxxXXXxxXXXXXXXXxx++
// +X++++::;++++++++++++++++++++++++xxxxxxxxxx++X+xxXXXXxXXXXXXxxXxx+++xXXXXXxxxx+xxxXXXXXXXX$$$$$Xx++x
// ;X+++.;::;;;::;;;.;;+:++++++++++xxxxxxxxxxxx+X+:;+++XxXxxxx+xxx++++xXXXXXxxxxx+++xxXXXXXXX$$$XXx+++x
// +X+++;::++::++::+:::+:+++++xxxxxxxxxxxxx+++++X;:;++xxXXxx+xXx++++xXXXxxXXxxxx++++xxxXX$$$XXXXXx++xxX
// ;X+++++++xx+++++++++++++xxxxxxxx+++++++++++++X+;;++xxxxxXxxxx+xxxXXxXXxxxxxx++++xxx$XX$XXXXxxxxxxxxx
// ;X++++xxxxxxxxxxxxx+++xx+x+++++++++++++++++++X+;;;;;++xxXXXXXxxXXXXXxxXXxxxxxxxXXXXXXXXXXX$XxxxxxxXX
// ;X+++xxxxxxxxxxxxxx+++++++;+x++++++++++++++++X+;;xxxxXXXX$$$XXXXXxxxXXXXXxxxXXXxxxXXXXXxxx+xxxxXXXXX
// +X++++++xxxxxxxxxxx+++++++++xx++xxx;+;;++++++X+++++xxxxxxxxxxXxxxxxXXxXxx++xxxx+++x+++++++++xxxxxxx:
// +X+;;++++++++++++++++++++++++++;+x+xxxx++;;++XXXXXXx+xxxxxXXXxxxxxxxxxXXx+++x++;;;;;;;;;;;++xxxxxx++
// +X+;;;;;;+++++++++++++++++++++;;;;;+++xxXX;++XXXXXXXXxxxXXxxxxxxxxxxxxxxXXxx+;;;;;;;;;;++;;++XXx;:::
// +X+;;;;;;;;;++++++++++++++++;;;;;;;;;X++X+;;+XXxXXxxxxxxxxxxxxxxxxxxxXXXXXXXx+++++;;:;;+xXXXxX+:;:.:
// xX;;;;;;;;;;;;;+++++++++;;;;;;;;+XxXxxXXx;;;+XXxxxxxxxxxxxxxxxxxxxxxXXxxxX$$Xxxxxxxx+++xxxxxXx++xxxx
// xX;;;;;;;;;;;;;;;;;;;;;;;;+xx+:;XXXXx++;;;;;+XXxXXXXXXXXXXXXxxXxxxXXX+++++xxX$Xxxxx+xxxxxxxxx+++++++
// xX;;;;;;;;;;;;;;;;;;;;::;XXxxXx;+XXx+:;;;;;++Xx;::;;+xxxx+xxxxXxXXxx++x+;;;+xXx+++;;;+;+XXx+++++++++
// XX;;;;;;;;;;::::::xXxxXx+xXXXXx::::::;;;;;;++X+:.::;+xxxx+;;;;Xx+++xx+xx;:;;+xx++;;;++xxxxXx++++++++
// XX;;;;:::::::::::XXXXXXX;++xx;::::::;;;;;;;;+X+;;;;;xxxxx+;;:::;;;;;;+x+::::;xx;++;;;;;;+xxxxxx+++++
// XX;:::::;::::::;+;xXXxX;::::::::::::::;;;;;;;X+;:;;;xxxxx+;;;;;;;;;++x;::.::;x+;::::::;;xxxxxxxxxxx+
// XX;::;;:::::::::;++:::::::::::::::::::::::::;X+;:;;+xXxxXx;;;;;++++;;::::::;;x;::....:;+xxxxxxxxxxxx
// XX;:::+;:::::::::;;::::::::+x++++++++;+;;;::;X+;::;;xxXXxx;;;+++;;;;:.:::;+xX;::::....+xxxxxxxxxxxxx
// $X;::::::;;;;;;:::.........+x++;;;++xxx+++;::X+;;;;;+xXXXx;;;;;;;;;;:++xXXXx:::::::..:+xxxxxxxxxxxxx
// XX;......:::::..............::::::::::::::..:X;::::::;xXXx;;::;::;;X$$$$$$+::::::::::xxxxxxxxxxxxxxx
// XX:.........................................:X;::::::::::;+++;;::;+XXXX$$+::........+xxxxxxxxxxxxxxx